# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: Wu-Char-Set
version: '0.0.0'
github: "ferynando7/Wu-Char-Set"
license: MIT
author: "Fernando Zhapa"
maintainer: "Fernando Zhapa"
# synopsis: A new Haskeleton package.
# description: Wu-Char-Set is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - containers
  - algebra
  - sized
  - matrix
  - random
  - random-shuffle
  source-dirs: library


executables:
  Wu-Char-Set:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - Wu-Char-Set
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  Wu-Char-Set-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - Wu-Char-Set
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  Wu-Char-Set-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - Wu-Char-Set
    - tasty
    - tasty-hspec
    - sized
    - tasty-hunit
    - random
    - random-shuffle
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
